# Generated by Django 3.0.7 on 2020-06-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Already Read', 'Already Read'), ('To Read', 'To Read'), ('Reading', 'Reading')], default='', max_length=20),
        ),
    ]
