# Generated by Django 3.0.7 on 2020-06-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200626_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('To Read', 'To Read'), ('Already Read', 'Already Read'), ('Reading', 'Reading')], default='', max_length=20),
        ),
    ]
